name: Share data between jobs
on: push
jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > file.txt
      - name: Clear GitHub Actions Cache
        run: rm -rf $HOME/.cache/actions
      - uses: actions/upload-artifact@v3.1.0  # Explicit version
        with:
          name: file
          path: file.txt

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v3.1.0  # Explicit version
        with:
          name: file
      - run: cat file.txt
